name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types:
            - opened
            - edited
            - reopened
            - synchronize
    workflow_dispatch:

jobs:

    check-commit-message-style:
        name: Check commit message style
        runs-on: ubuntu-latest
        steps:
            - name: Check
              uses: mristin/opinionated-commit-message@v2
              with:
                allow-one-liners: 'true'

    # @todo Run the black only once not for all builds.
    # check-python-formatting:
    #     name: Check the python formatting
    #     runs-on: ubuntu-latest
    #     steps:
    #        - name: Check

    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: [3.10.3]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install --editable ".[test,lint,docs]"
                  python -c "import cro.geneea"
            - name: Format the code
              run: |
                  black --check . --exclude docs/ data/
            - name: Sort the imports
              run: |
                  isort .
            - name: Lint the code
              run: |
                  #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: Test the code
              run: |
                  pytest -m domain
                  pytest -m client
